dist: trusty
sudo: false
language: go

go:
  - "1.10"

jobs:
  include:
    - stage: test
      script: bash tests/setup.sh && bash tests/run.sh
    - script: bash tests/setup.sh && bash tests/lint.sh
