#!/bin/sh -ef

# Runs golangci-lint locally using Docker without installing it on machine
# (see https://golangci-lint.run/welcome/install/#docker)

docker run -t --rm -v "$(pwd)":/app -v ~/.cache/golangci-lint/v1.59.1:/root/.cache -w /app golangci/golangci-lint:v1.59.1 golangci-lint run -v
