package kaitai

// Struct is the common interface guaranteed to be implemented by all types generated by
// Kaitai Struct compiler.
type Struct interface {
	// Kaitai_IO returns the stream object associated with the struct.
	//
	// This is deliberately named with a `Kaitai_` prefix and underscore to avoid conflicts
	// with other methods that may result from the attributes in Kaitai Struct type, e.g.
	// is a user will define attribute `i_o` this will conflict with the method `IO()`.
	Kaitai_IO() *Stream
}
